### ISSUE TITLE
Mined Stone Doesn't Disappear

### ISSUE THREAD

**Issue by SneakyTactician** [SneakyTactician/MagicalLife#123]
When workers finish mining stone, the stone is not removed.

**Comment by ABuonanni** [comment]
Has somebody already verified if this is a client or server issue?

**Comment by SneakyTactician** [comment]
No, however it is likely a server issue, not a client rendering issue.

Thomas

________________________________

**Comment by ABuonanni** [comment]
I'm having difficulties getting myself around the whole solutions. Is there any kind of "system design" documentation? Something that explains, even at an high level, how the system works?

**Comment by SneakyTactician** [comment]
There is a high level description of what each assembly/project does in this:
https://github.com/SneakyTactician/MagicalLife/tree/Crafting#assembly-descriptions

However, this is as detailed as it gets. Classes generally have decent (in my opinion) documentation, but I haven’t ever thought about creating a system design document.

Here’s a quick high level description of how the game works:

[MagicalLifeGUIWindows->Game1.cs] is the entry point for the GUI client
[MagicalLifeGUIWindows->Rendering->MapRenderer.cs] is the starting point for rendering graphics.
               This pulls the data for the world/map from [MagicalLifeAPIStandard->World->Data->World.cs] and renders it

[MagicalLifeClientStandard->Client.cs] has a event called ClientTick which triggers game logic such as entity movement, which is stored in [MagicalLifeAPIStandard->Entity->Movement->EntityWorldMovement.cs]
This client tick is triggered by messages from the server, which are sent from [MagicalLifeAPIStandard->Networking->Server->ServerSendRecieve.cs] and received by the client in [MagicalLifeAPIStandard->Networking->ClientSendRecieve.cs]
Serialization logic is stored in [MagicalLifeAPIStandard->Networking->Serialization->ProtoUtil.cs], and utilizes Protobuf-net for serialization. You can find examples of how to prepare a class for this kind of serialization on their Github site, or by finding one of the many classes that do so within this project.

Entity “jobs”/logic is managed by [MagicalLifeAPIStandard->Entity->AI->Task->TaskManager.cs]

Logging is done through a class called “MasterLog”, which is stored along with a lot of other file management classes in [MagicalLifeAPIStandard->Filing]

I’m sure that this will not completely tell you how the game works, but it should hopefully give you starting place to ask questions from.
Let me know what questions you have
