### ISSUE TITLE
Mod Support Last on Roadmap?

### ISSUE THREAD

**Issue by callowaysutton** [SneakyTactician/MagicalLife#20]
Is Mod Support the last thing you're going to work on? That's going to be really tough because when you want to embrace mods, then you want to have an open system/game that can be easily modified so having it to be the last thing to work on will add a ton of revising to be done on the code to.
Unless your just saying that in a random order...
I don't know, but to me it just would seem like a bad idea to make that the last thing to work on.

**Comment by SneakyTactician** [comment]
While the list was suppose to be a rough estimate of when things were suppose to happen, you make a good point. Throughout my time working on this project I have kept in mind mod support, so while it doesn't support mods currently it should be easier to implement than had I not. I should ALWAYS be thinking about mod support.

**Comment by callowaysutton** [comment]
Yay, this is good I really like this project and wanna see it flourish

**Comment by SneakyTactician** [comment]
Are you interested in helping out?

**Comment by callowaysutton** [comment]
I'm not really experienced in C# (although I am going to start taking classes on it, so maybe...)
If you ever need help on very low level things though I can always help out with that (experienced with C, C++, Rust, and x86/x64 Assemblies)

I'm not sure if Mono has optimized compiling, but next time when you compile a good tip is to use the `-o3` flag, it'll make the compiling a _lot_ longer but the game will end up being a lot more optimized and use less CPU cycles

**Comment by SneakyTactician** [comment]
Yeah. I updated the README to reflect that. I just mention it as a feature because some projects use windows forms or something that don't have hardware acceleration.
