### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by Batarian711** [SneakyTactician/MagicalLife#31]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by SneakyTactician** [comment]
Absolutely! Definitely need a logo.

**Comment by Batarian711** [comment]
I designed  icon style logo to reflect the name of Magical Life. Is there anything you want to add? What do you think? 
![magical](https://user-images.githubusercontent.com/41051393/42685871-e6a96d04-869c-11e8-9fe3-3b133df4586f.jpg)

**Comment by SneakyTactician** [comment]
It looks nice! Someday in the future (very least many months from now), when this game has some more iconic things in it, can I have you redo it to incorporate something iconic from the actual gameplay? Otherwise, I love it! I'll take it!

**Comment by Batarian711** [comment]
If you like it, I will send you pr.

**Comment by SneakyTactician** [comment]
I like it. Send away

**Comment by Batarian711** [comment]
I provided files. I sent pr.

**Comment by SneakyTactician** [comment]
Thank you!
