### ISSUE TITLE
In-Game Content

### ISSUE THREAD

**Issue by SneakyTactician** [SneakyTactician/MagicalLife#46]
This game needs more content such as water tiles, basic resource items, etc...

**Comment by a2937** [comment]
Can a list of content that needs to be added be made with some sort of chart demonstrating progress?

**Comment by SneakyTactician** [comment]
I'm afraid I haven't planned out yet what game content we need. I'll close this for now until most of the game "systems"/infrastructure is done, and then come back to this. We shouldn't be creating a ton of content until then anyways.
